# Generated by Django 6.0.5 on 2026-05-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('start_mya', models.IntegerField(verbose_name='Начало (млн лет назад)')),
                ('end_mya', models.IntegerField(verbose_name='Конец (млн лет назад)')),
            ],
            options={
                'verbose_name': 'Геологический период',
                'verbose_name_plural': 'Геологические периоды',
                'ordering': ['start_mya'],
            },
        ),
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('length_m', models.FloatField(verbose_name='Длина (метры)')),
                ('weight_t', models.FloatField(verbose_name='Вес (тонны)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.diet', verbose_name='Тип питания')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinosaurs', to='api.period', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Динозавр',
                'verbose_name_plural': 'Динозавры',
                'ordering': ['name'],
            },
        ),
    ]
